### ISSUE TITLE
Broken links on "Gruppenregeln"

### ISSUE THREAD

**Issue by jGleitz** [fsmi/o-phase.com#24]
Unfortunately, all external links given on the page "Gruppenregeln" are broken. These are in particular 
 * http://o-phase.com/o14/jobs
 * http://o-phase.com/o14/seminarraueme
 * http://www.asta-kit.de/sites/asta-usta.asta.uni-karlsruhe.de/files/Ma%C3%9Fnahmenkodex%20zu%20den%20O-Phasen.pdf

**Comment by toebbel** [comment]
have to reach out to the AStA about their link.

**Comment by toebbel** [comment]
done
