### ISSUE TITLE
Mehrfach orga Titel

### ISSUE THREAD

**Issue by JustKiddingCode** [fsmi/o-phase.com#25]
![ophase1](https://cloud.githubusercontent.com/assets/6041005/8552079/f96f2770-24da-11e5-9df0-0b8c72458fca.png)

**Comment by cbdevnet** [comment]
Vermutlich durch https://github.com/fsmi/o-phase.com/blob/master/lib/devise/strategies/ldap_authenticatable.rb#L23 ausgeloest

**Comment by maufl** [comment]
dang, mein Fehler ... ich fix das gleich
