### ISSUE TITLE
Support for UTF-8 CNs

### ISSUE THREAD

**Issue by darkblinded** [fsmi/o-phase.com#28]
Einige User können sich nicht anmelden. Dabei ist aufgefallen, dass diese User Umlaute in ihren Namen haben.
Laut Fehlermeldung im Log wird in lib/devise/strategies/ldap_authenticatable.rb in Zeile 32 eine Exception gefangen. Es ist allerdings unklar, wo die Exception geworfen wurde.
Mögliche Ursache könnte sein, dass in Zeile 14 unter anderem auch CN als Attribut abgefragt wird, was bei Umlaut-Namen base64 codiert ist.

**Comment by maufl** [comment]
Ich hab mal ein bisschen was probiert. Die Namen werden zwar nicht base64 codiert zurück geliefert, aber der string hat als encoding ASCII eingestelt. Ich erzwinge jetzt UTF-8 codierung, jetzt sollten Umlaute auch funktionieren.
Kann das mal jemand testen?

**Comment by jduepmeier** [comment]
Also richtiges logfile dazu liegt unter /var/log/apache2/www.o-phase.com/passenger.log

Fehlermeldung:
Error while authenticating a user via LDAP: "\xC3" from ASCII-8BIT to UTF-8

**Comment by maufl** [comment]
Sorry mein Fehler, jetzt nochmal probieren.
