### ISSUE TITLE
tutors cannot order shirts

### ISSUE THREAD

**Issue by toebbel** [fsmi/o-phase.com#36]
policy denies access to 'http://www.o-phase.com/o15ws/shirts' when logged in as tutor.

**Comment by toebbel** [comment]
should actually be fixed via 91c6f2c
@maufl I no nothing about the deployment. Could you please check which version is deployed ATM?

**Comment by maufl** [comment]
@toebbel The deployment command is in the Makefile. However, you lack the permissions to execute it :P I did a deployment just now. Maybe we should include the commit id somewhere in the website.

**Comment by toebbel** [comment]
deployed :)
