### ISSUE TITLE
negative shirt order count

### ISSUE THREAD

**Issue by toebbel** [fsmi/o-phase.com#38]
Shirt count in orga view has a negative count.

![1](https://cloud.githubusercontent.com/assets/779528/9807579/79b96672-5855-11e5-8443-70fbf834cc8b.png)

**Comment by maufl** [comment]
Maybe an order has a negative count? The model does not validate that count is positive or greater zero.

**Comment by toebbel** [comment]
There is a validator for that in the model :-?
![screenshot from 2015-09-11 07 43 05](https://cloud.githubusercontent.com/assets/779528/9807811/d2a74cc4-5858-11e5-8fa8-bc98f33f1ca4.png)

**Comment by maufl** [comment]
No I don't think so. I'll fix that soon.
